/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KH_Vista_97;
import KH_Control_97.KH_Constantes_97;
import KH_Control_97.KH_VariablesNomina_97;
import KH_Modelo_97.KH_Deducciones_97;
import KH_Modelo_97.KH_Informacion_97;
import KH_Modelo_97.KH_Prestaciones_97;
import KH_Modelo_97.KH_Totales_97;
import KH_Modelo_97.KH_Valores_97;
import java.awt.Dimension;
import java.awt.ScrollPane;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.System.exit;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author katherinne
 */
public class KH_FrmNomina_97 extends javax.swing.JFrame {
    
  
    /**
     * Creates new form KH_FrmNomina_97
     */
     //SECCIÓN DE INSTANCIACIÓN
     //Se crea una instancia de la clase Toolkit, para que la computadora genere un pitido
     //cuando se ingrese un carácter diferente de un número.
     public Toolkit t = Toolkit.getDefaultToolkit();
     private JScrollPane sp;
     /* public KH_VariablesNomina_97(String Nombres,String Mensaje,int DiasT,int NHEDU,int NHEN,
             int NHED, double SBMA, int Cedula,String ECedula, LocalDate FNacimiento,
             String LNacimiento,String ECivil,String Genero,int NHijos,String Seccion,
             LocalDate FechaA,double DiasV,double MesesV,double Edad,double VDia,double VHora,
             double VHEDiurna, double VHENocurna, double VHEDomFes,double SalDev,
             double Pension, double Salud, double Subtransporte, double PEdad,
             double PAlimentacion, double PProduccion,double PManutencion,double TDevengado,
             double TDeducido, double Neto, double THEDiurnas, double THENocturnas, 
             double THEDominicales){*/
     KH_VariablesNomina_97 ObjVariablesNomina = new KH_VariablesNomina_97("","",0,0,0,0,0.0,0,"",null,"","","",0,"",null,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
     KH_Informacion_97 ObjInformacion = new KH_Informacion_97();
     KH_Prestaciones_97 ObjPrestaciones = new KH_Prestaciones_97();
     KH_Totales_97 ObjTotales = new KH_Totales_97();
     KH_Valores_97 ObjValores = new KH_Valores_97();
     KH_Constantes_97 ObjConstantes=new KH_Constantes_97(); 
     KH_Deducciones_97 ObjDeducciones=new KH_Deducciones_97();
 
    public KH_FrmNomina_97() {
        initComponents();
        setLocationRelativeTo(this);//Ubica el formulario en el centro de la pantalla.
        LimpiaTexto(); 
        t = Toolkit.getDefaultToolkit();
        this.setTitle("Nómina Elsa Paton");
    }
    
public void LimpiaTexto() {
 txt_nombre.setText("");
 txt_Mensaje.setText("");
 txt_DiasT.setText("");
 txt_NHEDU.setText("");
 txt_NHEN.setText("");
 txt_NHED.setText("");
 txt_SBMA.setText("");
 txt_Cedula.setText("");
 txt_ECedula.setText("");
 txt_FNacimiento.setText("");
 txt_LNacimiento.setText("");
 txt_ECivil.setText("");
 txt_Genero.setText(""); 
 txt_LNacimiento.setText("");
 txt_Mensaje.setText("");
 txt_NHijos.setText("");
 txt_Neto.setText("");
 txt_PAlimentacion.setText("");
 txt_PEdad.setText("");
 txt_PManutencion.setText("");
 txt_PProduccion.setText("");
 txt_Pension.setText("");
 txt_SBMA.setText("");
 txt_SalDev.setText("");
 txt_Salud.setText("");
 txt_Seccion.setText("");
 txt_SubTransporte.setText("");
 txt_TDeducido.setText("");
 txt_TDevengado.setText("");
 txt_THEDiurnas.setText("");
 txt_THEDominicales.setText("");
 txt_THENocturnas.setText("");
 txt_VDia.setText("");
 txt_VHEDiurna.setText("");
 txt_VHEDomFes.setText("");
 txt_VHENocturna.setText("");
 txt_VHora.setText("");
 txt_nombre.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        txt_Mensaje = new javax.swing.JTextField();
        txt_DiasT = new javax.swing.JTextField();
        txt_NHEDU = new javax.swing.JTextField();
        txt_NHEN = new javax.swing.JTextField();
        txt_NHED = new javax.swing.JTextField();
        txt_SBMA = new javax.swing.JTextField();
        txt_Cedula = new javax.swing.JTextField();
        txt_ECedula = new javax.swing.JTextField();
        txt_FNacimiento = new javax.swing.JTextField();
        txt_LNacimiento = new javax.swing.JTextField();
        txt_ECivil = new javax.swing.JTextField();
        txt_Genero = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        SBMA = new javax.swing.JLabel();
        DiasTrabajados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_Calcular = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_NHijos = new javax.swing.JTextField();
        txt_Seccion = new javax.swing.JTextField();
        txt_FechaA = new javax.swing.JTextField();
        txt_DiasV = new javax.swing.JTextField();
        txt_MesesV = new javax.swing.JTextField();
        txt_Edad = new javax.swing.JTextField();
        txt_VDia = new javax.swing.JTextField();
        txt_VHora = new javax.swing.JTextField();
        txt_VHEDiurna = new javax.swing.JTextField();
        txt_VHENocturna = new javax.swing.JTextField();
        txt_VHEDomFes = new javax.swing.JTextField();
        txt_SalDev = new javax.swing.JTextField();
        txt_Pension = new javax.swing.JTextField();
        txt_Salud = new javax.swing.JTextField();
        txt_SubTransporte = new javax.swing.JTextField();
        txt_PEdad = new javax.swing.JTextField();
        txt_PAlimentacion = new javax.swing.JTextField();
        txt_PProduccion = new javax.swing.JTextField();
        txt_TDevengado = new javax.swing.JTextField();
        txt_TDeducido = new javax.swing.JTextField();
        txt_Neto = new javax.swing.JTextField();
        txt_THEDiurnas = new javax.swing.JTextField();
        txt_THENocturnas = new javax.swing.JTextField();
        txt_THEDominicales = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_PManutencion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 13, 0, 13, 0, 13, 0, 13, 0};
        jPanel1Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel1.setLayout(jPanel1Layout);

        txt_nombre.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_nombre, gridBagConstraints);

        txt_Mensaje.setForeground(new java.awt.Color(0, 0, 255));
        txt_Mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MensajeActionPerformed(evt);
            }
        });
        txt_Mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MensajeKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 148;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_Mensaje, gridBagConstraints);

        txt_DiasT.setForeground(new java.awt.Color(0, 0, 255));
        txt_DiasT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DiasTKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_DiasT, gridBagConstraints);

        txt_NHEDU.setForeground(new java.awt.Color(0, 0, 255));
        txt_NHEDU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NHEDUKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        jPanel1.add(txt_NHEDU, gridBagConstraints);

        txt_NHEN.setForeground(new java.awt.Color(102, 102, 102));
        txt_NHEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NHENActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_NHEN, gridBagConstraints);

        txt_NHED.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_NHED, gridBagConstraints);

        txt_SBMA.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_SBMA, gridBagConstraints);

        txt_Cedula.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txt_Cedula, gridBagConstraints);

        txt_ECedula.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        jPanel1.add(txt_ECedula, gridBagConstraints);

        txt_FNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        txt_FNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FNacimientoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        jPanel1.add(txt_FNacimiento, gridBagConstraints);

        txt_LNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        jPanel1.add(txt_LNacimiento, gridBagConstraints);

        txt_ECivil.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        jPanel1.add(txt_ECivil, gridBagConstraints);

        txt_Genero.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 44;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        jPanel1.add(txt_Genero, gridBagConstraints);

        Nombre.setBackground(new java.awt.Color(102, 102, 255));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        Nombre.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(Nombre, gridBagConstraints);

        SBMA.setBackground(new java.awt.Color(102, 102, 255));
        SBMA.setForeground(new java.awt.Color(255, 255, 255));
        SBMA.setText("SBMA");
        SBMA.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(SBMA, gridBagConstraints);

        DiasTrabajados.setBackground(new java.awt.Color(102, 102, 255));
        DiasTrabajados.setForeground(new java.awt.Color(255, 255, 255));
        DiasTrabajados.setText("Días trabajados");
        DiasTrabajados.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(DiasTrabajados, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horas extras diurnas");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Valor día");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Total horas extras diurnas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Salario devengado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Subsidio de transporte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Salud");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Total devengado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Pension");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Neto a pagar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel13.setText("Mensaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel13, gridBagConstraints);

        btn_Calcular.setBackground(new java.awt.Color(255, 255, 255));
        btn_Calcular.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btn_Calcular.setForeground(new java.awt.Color(255, 51, 153));
        btn_Calcular.setText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 152;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 125;
        jPanel1.add(btn_Calcular, gridBagConstraints);

        btn_Limpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Limpiar.setForeground(new java.awt.Color(51, 102, 255));
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 156;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 128;
        jPanel1.add(btn_Limpiar, gridBagConstraints);

        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(0, 102, 51));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 160;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 140;
        jPanel1.add(btn_Salir, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horas extras nocturnas");
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Horas extras dominicales");
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel14.setText("Valor hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 76;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel14, gridBagConstraints);

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cedula");
        jLabel15.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel15, gridBagConstraints);

        jLabel16.setText("Edad");
        jLabel16.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel16, gridBagConstraints);

        jLabel17.setBackground(new java.awt.Color(102, 102, 255));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Expedicion de Cedula");
        jLabel17.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel17, gridBagConstraints);

        jLabel18.setBackground(new java.awt.Color(102, 102, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Seccion");
        jLabel18.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel18, gridBagConstraints);

        jLabel19.setBackground(new java.awt.Color(102, 102, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha de nacimiento");
        jLabel19.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel19, gridBagConstraints);

        jLabel20.setText("Meses vividos");
        jLabel20.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Dias vividos");
        jLabel21.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel21, gridBagConstraints);

        jLabel22.setBackground(new java.awt.Color(102, 102, 255));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha actual");
        jLabel22.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel22, gridBagConstraints);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Estado civil");
        jLabel23.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel23, gridBagConstraints);

        jLabel24.setBackground(new java.awt.Color(102, 102, 255));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Numero de hijos");
        jLabel24.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel24, gridBagConstraints);

        jLabel25.setBackground(new java.awt.Color(102, 102, 255));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Lugar de nacimiento");
        jLabel25.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel25, gridBagConstraints);

        jLabel26.setBackground(new java.awt.Color(102, 102, 255));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Genero ");
        jLabel26.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel26, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 48;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        jPanel1.add(txt_NHijos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 52;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_Seccion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 56;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_FechaA, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 60;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_DiasV, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 64;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_MesesV, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 68;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_Edad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 72;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_VDia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 76;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_VHora, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 80;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_VHEDiurna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 84;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_VHENocturna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 88;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_VHEDomFes, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 92;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_SalDev, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 96;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_Pension, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 100;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_Salud, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 104;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_SubTransporte, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 108;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_PEdad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 112;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_PAlimentacion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 116;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_PProduccion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 124;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_TDevengado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 128;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_TDeducido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 132;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        jPanel1.add(txt_Neto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 136;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_THEDiurnas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 140;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_THENocturnas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 144;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txt_THEDominicales, gridBagConstraints);

        jLabel27.setText("Valor hora extra diurna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel27, gridBagConstraints);

        jLabel28.setText("Valor de hora extra nocturna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel28, gridBagConstraints);

        jLabel29.setText("Valor de hora extra dominical y festivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 88;
        jPanel1.add(jLabel29, gridBagConstraints);

        jLabel30.setText("Prima de edad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel30, gridBagConstraints);

        jLabel31.setText("Prima de alimentacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel31, gridBagConstraints);

        jLabel32.setText("Prima de produccion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel32, gridBagConstraints);

        jLabel33.setText("Total deducido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel33, gridBagConstraints);

        jLabel34.setText("Total horas extras nocturnas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel34, gridBagConstraints);

        jLabel35.setText("Total horas extras dominicales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel35, gridBagConstraints);

        jLabel36.setText("Prima de manutencion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel36, gridBagConstraints);

        txt_PManutencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PManutencionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 120;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txt_PManutencion, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 640, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MensajeActionPerformed

    private void txt_FNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FNacimientoActionPerformed

    private void txt_NHEDUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NHEDUKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.'
     && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() !=
     KeyEvent.VK_ENTER) {
     //En caso que se ingrese un carácter diferente de un número.
     t.beep();//Genera un pitido.
     //El método e.consume() hace que esa pulsación de tecla se rechace y el JTextField
     //no la procese.
     evt.consume();
     //Despliega un mensaje de error.
     JOptionPane.showMessageDialog(null, "!Error!\n Solo puede ingresar números.","Entrada de datos inválida.", JOptionPane.ERROR_MESSAGE);
     txt_NHEDU.setText("");//Limpia la caja de texto.    
        }
    }//GEN-LAST:event_txt_NHEDUKeyTyped

    private void txt_MensajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MensajeKeyTyped
        // TODO add your handling code here:
     //Este método filtra la entrada de carácteres en la caja de texto
     //para que solo se puedan ingresar números.
     if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.'
     && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() !=
     KeyEvent.VK_ENTER) {
     //En caso que se ingrese un carácter diferente de un número.
      t.beep(); //Genera un pitido.
     //El método e.consume() hace que esa pulsación de tecla se rechace y el JTextField no la
     //procese.
     evt.consume();
     //Despliega un mensaje de error.
     JOptionPane.showMessageDialog(null, "!Error!\n Solo puede ingresar números.","Entrada de datos inválida.", JOptionPane.ERROR_MESSAGE);
     txt_Mensaje.setText("");//Limpia la caja de texto.
     }
    }//GEN-LAST:event_txt_MensajeKeyTyped

    private void txt_DiasTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiasTKeyTyped

    // TODO add your handling code here:
     //Este método filtra la entrada de carácteres en la caja de texto
     //para que solo se puedan ingresar números.
     if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.'
     && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() !=
     KeyEvent.VK_ENTER) {
     //En caso que se ingrese un carácter diferente de un número.
     t.beep();//Genera un pitido.
     //El método e.consume() hace que esa pulsación de tecla se rechace y el JTextField no la
     // procese.
     evt.consume();
     //Despliega un mensaje de error.
     JOptionPane.showMessageDialog(null, "!Error!\n Solo puede ingresar números.","Entrada de datos inválida.", JOptionPane.ERROR_MESSAGE);
     txt_DiasT.setText("");//Limpia la caja de texto.

 } 
        
    }//GEN-LAST:event_txt_DiasTKeyTyped

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        // TODO add your handling code here:
        //-----------------------------------------------------------
 // SECCIÓN DE ENTRADA DE DATOS
 //-----------------------------------------------------------
 //1. Nombres.
 ObjVariablesNomina.setNombres(txt_nombre.getText());
 //2. Salario básico mensual asignado.
 ObjVariablesNomina.setSBMA(Double.parseDouble(txt_SBMA.getText()));
 //3. Días trabajados.
 ObjVariablesNomina.setDiasT(Integer.parseInt(txt_DiasT.getText()));
 //4. Número de horas extras.
 ObjVariablesNomina.setNHEDU(Integer.parseInt(txt_NHEDU.getText()));
 ObjVariablesNomina.setNHEN(Integer.parseInt(txt_NHEN.getText()));
 ObjVariablesNomina.setNHED(Integer.parseInt(txt_NHED.getText()));
 ObjVariablesNomina.setCedula(Integer.parseInt(txt_Cedula.getText()));
 ObjVariablesNomina.setECedula(txt_ECedula.getText());
 ObjVariablesNomina.setFNacimiento(LocalDate.parse(txt_FNacimiento.getText(), 
                                   DateTimeFormatter.ofPattern("dd/MM/yyyy")));
 ObjVariablesNomina.setFechaA(LocalDate.parse(txt_FechaA.getText(), 
                                   DateTimeFormatter.ofPattern("dd/MM/yyyy")));
 ObjVariablesNomina.setLNacimiento(txt_LNacimiento.getText());
 ObjVariablesNomina.setECivil(txt_ECivil.getText());
 ObjVariablesNomina.setGenero(txt_Genero.getText());
 ObjVariablesNomina.setNHijos(Integer.parseInt(txt_NHijos.getText()));
 ObjVariablesNomina.setSeccion(txt_Seccion.getText());
 
 //-----------------------------------------------------------
 // SECCION CALCULO DE DATOS
 //-----------------------------------------------------------
 
 if ((ObjVariablesNomina.getSBMA() >= ObjConstantes.SMLV) && (ObjVariablesNomina.getSBMA() <= (20 * ObjConstantes.SMLV))) {
 /*
 Si Salario básico mensual asignado (SBMA) :>=SMLV y <= (20 x SMLV).*/
 
    if ((ObjVariablesNomina.getDiasT() >= 0)&& (ObjVariablesNomina.getDiasT() <= 30)) {
     //Si Días trabajados (DiasT) :>=0 y <=30.
        if (((ObjVariablesNomina.getNHED()+ObjVariablesNomina.getNHEN()+ObjVariablesNomina.getNHEDU())>= 0) && 
             ((ObjVariablesNomina.getNHED()+ObjVariablesNomina.getNHEN()+ObjVariablesNomina.getNHEDU()) <= 40)){
               //ObjVariablesNomina.setFechaA(ObjInformacion.Hoy());
               ObjVariablesNomina.setDiasV(ObjInformacion.DiasVividos( ObjVariablesNomina.getFNacimiento()));
               ObjVariablesNomina.setMesesV(ObjInformacion.MesesVividos(ObjVariablesNomina.getDiasV()));
               ObjVariablesNomina.setEdad(ObjInformacion.Edad(ObjVariablesNomina.getDiasV()));
               ObjVariablesNomina.setVDia(ObjValores.KH_CalcVDia_97(ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setVHora(ObjValores.KH_CalcVHora_97(ObjVariablesNomina.getVDia()));
               ObjVariablesNomina.setVHEDiurna(ObjValores.KH_CalcHEDiurna_97(ObjVariablesNomina.getVHora()));
               ObjVariablesNomina.setVHENocturna(ObjValores.KH_CalcHENocturna_97(ObjVariablesNomina.getVHora()));
               ObjVariablesNomina.setVHEDomFes(ObjValores.KH_CalcHEDomFes_97(ObjVariablesNomina.getVHora()));
               ObjVariablesNomina.setPension(ObjDeducciones.KH_CalcPension_97(ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setSalud(ObjDeducciones.KH_CalcSalud_97(ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setPension(ObjDeducciones.KH_CalcPension_97(ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setPEdad(ObjPrestaciones.CalcPEdad(ObjVariablesNomina.getEdad(),ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setPAlimentacion(ObjPrestaciones.KH_CalcPAlimentacion_97(ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setPProduccion(ObjPrestaciones.KH_CalcPProduccion_97(ObjVariablesNomina.getSeccion(),ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setPManutencion(ObjPrestaciones.KH_CalcPManutencion_97(ObjVariablesNomina.getNHijos(),ObjVariablesNomina.getSBMA()));
               ObjVariablesNomina.setTDeducido(ObjTotales.KH_CalcTDeducido_97(ObjVariablesNomina.getPension(),ObjVariablesNomina.getSalud(),ObjDeducciones.KH_CalcRetefuente_97(ObjVariablesNomina.getSBMA())));
               ObjVariablesNomina.setTHEDiurnas(ObjTotales.KH_CalcTHEDiurnas_97(ObjVariablesNomina.getVHEDiurna(), ObjVariablesNomina.getNHEDU()));
               ObjVariablesNomina.setTHENocturnas(ObjTotales.KH_CalcTHENocturnas_97(ObjVariablesNomina.getVHENocturna(), ObjVariablesNomina.getNHEN()));
               ObjVariablesNomina.setTHEDominicales(ObjTotales.KH_CalcTHEDominicales_97(ObjVariablesNomina.getVHEDomFes(), ObjVariablesNomina.getNHED()));
               ObjVariablesNomina.setSalDev(ObjTotales.KH_CalcSalarioDev_97(ObjVariablesNomina.getDiasT(), ObjVariablesNomina.getVDia()));
               ObjVariablesNomina.setTDevengado(ObjTotales.KH_CalcTDevengado_97(ObjVariablesNomina.getSalDev(), ObjVariablesNomina.getPAlimentacion(), 
                                                ObjVariablesNomina.getPProduccion(), ObjVariablesNomina.getPManutencion(), ObjVariablesNomina.getSubTransporte(), 
                                                ObjVariablesNomina.getPEdad(), ObjVariablesNomina.getTHEDiurnas(), 
                                                ObjVariablesNomina.getTHENocturnas(), ObjVariablesNomina.getTHEDominicales()));
               ObjVariablesNomina.setNeto(ObjTotales.KH_CalcNeto_97(ObjVariablesNomina.getTDevengado(),ObjVariablesNomina.getTDeducido()));

               //-----------------------------------------------------------
               // SECCION SALIDA DE DATOS
               //-----------------------------------------------------------
            /*   txt_NHEN.setText(String.valueOf(ObjVariablesNomina.getVrDia()));
               txt_NHED.setText(String.valueOf(ObjVariablesNomina.getVrHE()));
               txt_SBMA.setText(String.valueOf(ObjVariablesNomina.getSalDev()));
               txt_Cedula.setText(String.valueOf(ObjVariablesNomina.getSubsTransp()));
               txt_ECedula.setText(String.valueOf(ObjVariablesNomina.getTotEx()));
               txt_FNacimiento.setText(String.valueOf(ObjVariablesNomina.getTotDev()));
               txt_LNacimiento.setText(String.valueOf(ObjVariablesNomina.getSegSoc()));
               txt_ECivil.setText(String.valueOf(ObjVariablesNomina.getNeto()));
               txt_Genero.setText(ObjVariablesNomina.getMensaje());*/
            
             
               txt_DiasT.setText(""+ObjVariablesNomina.getDiasT());
               txt_DiasV.setText(""+ObjVariablesNomina.getDiasV());
               txt_Mensaje.setText(""+ObjVariablesNomina.getMensaje());
               txt_MesesV.setText(String.format("%.2f", ObjVariablesNomina.getMesesV()));
               txt_Neto.setText(String.format("%.2f", ObjVariablesNomina.getNeto()));
               txt_PAlimentacion.setText(String.format("%.2f", ObjVariablesNomina.getPAlimentacion()));
               txt_PEdad.setText(String.format("%.2f", ObjVariablesNomina.getPEdad()));
               txt_PManutencion.setText(String.format("%.2f", ObjVariablesNomina.getPManutencion()));
               txt_PProduccion.setText(String.format("%.2f", ObjVariablesNomina.getPProduccion()));
               txt_Pension.setText(String.format("%.2f", ObjVariablesNomina.getPension()));
               txt_SalDev.setText(String.format("%.2f", ObjVariablesNomina.getSalDev()));
               txt_Salud.setText(String.format("%.2f", ObjVariablesNomina.getSalud()));
               txt_SubTransporte.setText(String.format("%.2f", ObjVariablesNomina.getSubTransporte()));
               txt_TDeducido.setText(String.format("%.2f", ObjVariablesNomina.getTDeducido()));
               txt_TDevengado.setText(String.format("%.2f", ObjVariablesNomina.getTDevengado()));
               txt_THEDiurnas.setText(String.format("%.2f", ObjVariablesNomina.getTHEDiurnas()));
               txt_THEDominicales.setText(String.format("%.2f", ObjVariablesNomina.getTHEDominicales()));
               txt_THENocturnas.setText(String.format("%.2f", ObjVariablesNomina.getTHENocturnas()));
               txt_VDia.setText(String.format("%.2f", ObjVariablesNomina.getVDia()));
               txt_VHEDiurna.setText(String.format("%.2f", ObjVariablesNomina.getVHEDiurna()));
               txt_VHEDomFes.setText(String.format("%.2f", ObjVariablesNomina.getVHEDomFes()));
               txt_VHENocturna.setText(String.format("%.2f", ObjVariablesNomina.getVHENocturna()));
               txt_VHora.setText(String.format("%.2f", ObjVariablesNomina.getVHora()));
                txt_Mensaje.setText("Datos de nomina correctamente calculados");
            
            
            
        }//Fin filtro Número de horas extras (NHE) :>=0 y <=40.
        else {
        JOptionPane.showMessageDialog(null, "!Error! el valor de las horas extras está fuera de rango."
        + "\n(NHE>=0) y (NHE<=40).", "Nómina Elsa Patón",
       JOptionPane.WARNING_MESSAGE);
       txt_NHEDU.requestFocus();//Se ubica en el JTextField para coregir el dato ingresado.
        }//Fin Else
        
    }//Fin Si Días trabajados (DiasT) :>=0 y <=30.
    else{
        JOptionPane.showMessageDialog(null, "!Error! el valor de los días trabajados está fuera de rango."
        + "\n(Días trabajados >=0) y (Días trabajados <=30).", "Nómina Elsa Patón",
       JOptionPane.WARNING_MESSAGE);
        txt_DiasT.requestFocus(); //Se ubica en el JTextField para coregir el dato ingresado.
        } //Fin Else
  }//Fin Si Salario básico mensual asignado (SBMA) :>=SMLV y <= (20 x SMLV).
  else{
        JOptionPane.showMessageDialog(null, "!Error! el valor del SBMA fuera de rango."
        + "\n(SBMA>=SMLV) y (SBMA<= (20 x SMLV))."
        + "\nSalario mínimo legal vigente (SMLV) =" + ObjConstantes.SMLV,
        "Nómina Elsa Patón", JOptionPane.WARNING_MESSAGE); 
        txt_Mensaje.requestFocus();//Se ubica en el JTextField para coregir el dato ingresado.
     }//Fin Else
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        LimpiaTexto(); 
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
  JOptionPane.showMessageDialog(null, "Gracias por utilizar esta apliccion", "Nómina Elsa Patón",
JOptionPane.WARNING_MESSAGE);
        exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void txt_NHENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NHENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NHENActionPerformed

    private void txt_PManutencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PManutencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PManutencionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KH_FrmNomina_97.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KH_FrmNomina_97.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KH_FrmNomina_97.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KH_FrmNomina_97.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KH_FrmNomina_97().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiasTrabajados;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel SBMA;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_DiasT;
    private javax.swing.JTextField txt_DiasV;
    private javax.swing.JTextField txt_ECedula;
    private javax.swing.JTextField txt_ECivil;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_FNacimiento;
    private javax.swing.JTextField txt_FechaA;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_LNacimiento;
    private javax.swing.JTextField txt_Mensaje;
    private javax.swing.JTextField txt_MesesV;
    private javax.swing.JTextField txt_NHED;
    private javax.swing.JTextField txt_NHEDU;
    private javax.swing.JTextField txt_NHEN;
    private javax.swing.JTextField txt_NHijos;
    private javax.swing.JTextField txt_Neto;
    private javax.swing.JTextField txt_PAlimentacion;
    private javax.swing.JTextField txt_PEdad;
    private javax.swing.JTextField txt_PManutencion;
    private javax.swing.JTextField txt_PProduccion;
    private javax.swing.JTextField txt_Pension;
    private javax.swing.JTextField txt_SBMA;
    private javax.swing.JTextField txt_SalDev;
    private javax.swing.JTextField txt_Salud;
    private javax.swing.JTextField txt_Seccion;
    private javax.swing.JTextField txt_SubTransporte;
    private javax.swing.JTextField txt_TDeducido;
    private javax.swing.JTextField txt_TDevengado;
    private javax.swing.JTextField txt_THEDiurnas;
    private javax.swing.JTextField txt_THEDominicales;
    private javax.swing.JTextField txt_THENocturnas;
    private javax.swing.JTextField txt_VDia;
    private javax.swing.JTextField txt_VHEDiurna;
    private javax.swing.JTextField txt_VHEDomFes;
    private javax.swing.JTextField txt_VHENocturna;
    private javax.swing.JTextField txt_VHora;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
